// src/utility/actionTypes.js
const ADD_TO_BASKET = "ADD_TO_BASKET";
const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
const UPDATE_QUANTITY = "UPDATE_QUANTITY";
const SET_USER = "SET_USER";

export const Type = { ADD_TO_BASKET, REMOVE_FROM_BASKET, UPDATE_QUANTITY,SET_USER };
